changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
    - title: Exciting New Features
      labels:
        - Semver-Minor
        - feature
    - title: Change Feature
      labels:
        - Semver-Patch
    - title: Bug Fix
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
